/**
 * Mock Compliance Data – For development when SmartPay backend is unavailable
 * Location: src/lib/api/compliance-mock.ts
 * Used by: compliance.ts as fallback
 */

import type { KRIMetrics, BonReportQueue, ComplianceAlertResponse, ComplianceEvent } from '@/lib/types/compliance';

export const mockKRIMetrics: KRIMetrics = {
  transactionSuccessRate: {
    id: 1,
    name: 'Transaction Success Rate',
    current: 99.7,
    target: 99.5,
    unit: '%',
    status: 'GOOD',
    trend: [99.6, 99.5, 99.8, 99.6, 99.7, 99.8, 99.7],
    lastUpdated: new Date().toISOString(),
    description: 'Percentage of successful transactions vs total attempted',
    dataSource: 'transactions table',
  },
  systemUptime: {
    id: 2,
    name: 'System Uptime',
    current: 99.91,
    target: 99.9,
    unit: '%',
    status: 'GOOD',
    trend: [99.89, 99.92, 99.91, 99.90, 99.91, 99.92, 99.91],
    lastUpdated: new Date().toISOString(),
    description: 'System availability percentage over the last 30 days',
    dataSource: 'system_uptime_metrics',
  },
  twoFAEnforcementRate: {
    id: 3,
    name: '2FA Enforcement Rate',
    current: 98.5,
    target: 100,
    unit: '%',
    status: 'WARNING',
    trend: [97.5, 98.0, 98.2, 98.3, 98.4, 98.5, 98.5],
    lastUpdated: new Date().toISOString(),
    description: 'Percentage of users with 2FA enabled',
    dataSource: 'user_sessions',
  },
  fraudDetectionAccuracy: {
    id: 4,
    name: 'Fraud Detection Accuracy',
    current: 87.5,
    target: 85,
    unit: '%',
    status: 'GOOD',
    trend: [86.0, 86.5, 87.0, 87.2, 87.5, 87.8, 87.5],
    lastUpdated: new Date().toISOString(),
    description: 'True positive rate of fraud detection system',
    dataSource: 'fraud_events',
  },
  customerComplaintRate: {
    id: 5,
    name: 'Customer Complaint Rate',
    current: 1.2,
    target: 2,
    unit: '%',
    status: 'GOOD',
    trend: [1.5, 1.4, 1.3, 1.2, 1.2, 1.1, 1.2],
    lastUpdated: new Date().toISOString(),
    description: 'Customer complaints as percentage of active users',
    dataSource: 'complaints',
  },
  averageResolutionTime: {
    id: 6,
    name: 'Average Resolution Time',
    current: 18.5,
    target: 24,
    unit: 'hours',
    status: 'GOOD',
    trend: [20.0, 19.5, 19.0, 18.5, 18.0, 18.5, 18.5],
    lastUpdated: new Date().toISOString(),
    description: 'Average time to resolve compliance alerts',
    dataSource: 'compliance_alerts',
  },
  regulatoryBreachCount: {
    id: 7,
    name: 'Regulatory Breach Count',
    current: 0,
    target: 0,
    unit: 'count',
    status: 'GOOD',
    trend: [0, 0, 0, 0, 0, 0, 0],
    lastUpdated: new Date().toISOString(),
    description: 'Number of regulatory breaches in the last 30 days',
    dataSource: 'compliance_violations',
  },
  securityIncidentCount: {
    id: 8,
    name: 'Security Incident Count',
    current: 2,
    target: 5,
    unit: 'count',
    status: 'GOOD',
    trend: [3, 2, 2, 1, 2, 2, 2],
    lastUpdated: new Date().toISOString(),
    description: 'Security incidents per month',
    dataSource: 'security_incidents',
  },
  dataBackupSuccessRate: {
    id: 9,
    name: 'Data Backup Success Rate',
    current: 100,
    target: 100,
    unit: '%',
    status: 'GOOD',
    trend: [100, 100, 100, 100, 100, 100, 100],
    lastUpdated: new Date().toISOString(),
    description: 'Percentage of successful automated backups',
    dataSource: 'backup_logs',
  },
  apiResponseTimeP95: {
    id: 10,
    name: 'API Response Time (P95)',
    current: 185,
    target: 200,
    unit: 'ms',
    status: 'GOOD',
    trend: [190, 188, 185, 182, 185, 187, 185],
    lastUpdated: new Date().toISOString(),
    description: '95th percentile API response time',
    dataSource: 'api_metrics',
  },
  agentNetworkUptime: {
    id: 11,
    name: 'Agent Network Uptime',
    current: 99.2,
    target: 99,
    unit: '%',
    status: 'GOOD',
    trend: [99.0, 99.1, 99.2, 99.1, 99.2, 99.3, 99.2],
    lastUpdated: new Date().toISOString(),
    description: 'Percentage of active agent locations',
    dataSource: 'agent_locations',
  },
  trustReconciliationPass: {
    id: 12,
    name: 'Trust Reconciliation Pass',
    current: 100,
    target: 100,
    unit: '%',
    status: 'GOOD',
    trend: [100, 100, 100, 100, 100, 100, 100],
    lastUpdated: new Date().toISOString(),
    description: 'Daily trust account reconciliation pass rate',
    dataSource: 'reconciliation_log',
  },
};

export const mockBonReportQueue: BonReportQueue = {
  reports: [
    {
      id: 'BN-2026-001',
      reportType: 'INCIDENT',
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      deadline: new Date(Date.now() + 21 * 60 * 60 * 1000).toISOString(),
      status: 'PENDING',
      retryCount: 0,
      metadata: {
        period: 'March 2026',
      },
    },
    {
      id: 'BN-2026-002',
      reportType: 'KRI',
      createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      deadline: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'SUBMITTED',
      retryCount: 0,
      submittedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      metadata: {
        period: 'Q1 2026',
      },
    },
    {
      id: 'BN-2026-003',
      reportType: 'TRANSACTION',
      createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
      deadline: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      status: 'OVERDUE',
      retryCount: 2,
      errorMessage: 'Connection timeout to BoN API',
      metadata: {
        period: 'February 2026',
      },
    },
  ],
  pendingCount: 1,
  overdueCount: 1,
};

export const mockComplianceAlerts: ComplianceAlertResponse = {
  alerts: [
    {
      id: 'ALERT-001',
      type: 'KRI_BREACH',
      severity: 'WARNING',
      title: '2FA Enforcement Below Target',
      message: '2FA enforcement rate is at 98.5%, below the 100% target. 15 users without 2FA enabled.',
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      metadata: {
        kriId: 3,
      },
    },
    {
      id: 'ALERT-002',
      type: 'BON_OVERDUE',
      severity: 'CRITICAL',
      title: 'BoN Report Overdue',
      message: 'Transaction report BN-2026-003 is 6 hours past deadline. Submit immediately.',
      createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      metadata: {
        reportId: 'BN-2026-003',
      },
    },
    {
      id: 'ALERT-003',
      type: 'SECURITY_INCIDENT',
      severity: 'INFO',
      title: 'Failed Login Attempts',
      message: 'Elevated failed login attempts detected from IP 41.182.*.* (Windhoek). Monitoring.',
      createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
  ],
  activeCount: 3,
  criticalCount: 1,
};

export const mockComplianceEvents: ComplianceEvent[] = [
  {
    id: 'EVENT-001',
    title: 'Q1 2026 KRI Report',
    type: 'KRI_REPORT',
    start: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    end: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    allDay: true,
    description: 'Quarterly KRI report submission to Bank of Namibia',
    status: 'PENDING',
  },
  {
    id: 'EVENT-002',
    title: 'Daily Trust Reconciliation',
    type: 'TRUST_RECONCILIATION',
    start: new Date(),
    end: new Date(),
    allDay: true,
    description: 'Daily reconciliation of trust account balances',
    status: 'PENDING',
  },
  {
    id: 'EVENT-003',
    title: 'Security Incident Report',
    type: 'INCIDENT_REPORT',
    start: new Date(Date.now() + 18 * 60 * 60 * 1000),
    end: new Date(Date.now() + 18 * 60 * 60 * 1000),
    allDay: false,
    description: '24-hour incident report deadline',
    status: 'PENDING',
  },
  {
    id: 'EVENT-004',
    title: 'Annual Audit Submission',
    type: 'AUDIT_SUBMISSION',
    start: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    end: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    allDay: true,
    description: 'Annual audit report submission to BoN',
    status: 'PENDING',
  },
];
