/**
 * Common – Branded, composed components (Button, Card, Badge, etc.)
 * Re-exports from ui/ for the suggested boilerplate structure.
 */

export {
  Button,
  Badge,
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
  StatusBadge,
  MetricCard,
  EmptyState,
  QuickAction,
  QuickActionsGrid,
  PillButton,
  PillGroup,
  CircleButton,
  FAB,
  SearchHeader,
  SectionHeader,
  StatusPill,
  DriverCard,
  VehicleCard,
  EntityCard,
  CardGrid,
  type ButtonProps,
  type BadgeProps,
  type BadgeVariant,
  type BadgeSize,
  type CardProps,
  type StatusBadgeProps,
  type StatusVariant,
  type StatusSize,
  type MetricCardProps,
  type MetricVariant,
  type EmptyStateProps,
  type QuickActionProps,
  type QuickActionsGridProps,
  type PillButtonProps,
  type PillGroupProps,
  type CircleButtonProps,
  type FabProps,
  type FabPosition,
  type SearchHeaderProps,
  type SectionHeaderProps,
  type StatusPillProps,
  type StatusPillVariant,
  type DriverCardProps,
  type VehicleCardProps,
  type EntityCardProps,
  type EntityCardStat,
  type CardGridProps,
} from '../ui';
